# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: 9.15.0
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - run: pnpm install

      # Generate Prisma Client before caching
      - name: Generate Prisma Client
        run: cd apps/web && pnpm prisma:generate
      
      # Cache Prisma (more specific paths)
      - name: Cache Prisma
        uses: actions/cache@v3
        with:
          path: apps/web/node_modules/.prisma/client
          key: ${{ runner.os }}-prisma-client-${{ hashFiles('apps/web/prisma/schema.prisma') }}
          restore-keys: |
            ${{ runner.os }}-prisma-client-
      
      # Cache Next.js (more specific paths)
      - name: Cache Next.js
        uses: actions/cache@v3
        with:
          path: apps/web/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('apps/web/next.config.ts') }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-
      
      - run: pnpm type-check
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build